version: '2'
services:
    fpm:
        build: devops/php
        volumes:
            - ./:/var/www/html

        ports:
            - "9000:9000"
        links:
            - mysql

    nginx:
        build: devops/nginx
        volumes:
            - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./devops/nginx/app.vhost:/etc/nginx/conf.d/app.vhost
            - ./:/var/www/html
        ports:
            - "80:80"
        links:
            - fpm

    mysql:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=a2c_cms